"""Rendering & Packaging Service.

Handles watermark application, text overlays, and ZIP bundle creation.
Generated assets are stored temporarily with auto-delete after TTL.

PRIVACY: Generated assets auto-delete after 4 hours.
"""

from __future__ import annotations

import io
import zipfile
from pathlib import Path
from typing import Any, Optional

from app.logging_config import get_logger

logger = get_logger(__name__)


class Renderer:
    """Handles image post-processing and watermarking."""

    WATERMARK_TEXT = "Generated by Git Phantom Scope - gitphantomscope.dev"

    def add_watermark(self, image_bytes: bytes, tier: str = "free") -> bytes:
        """Add watermark to generated images.

        Free tier: Visible watermark
        Pro tier: Small, subtle watermark
        Enterprise: No watermark
        """
        if tier == "enterprise":
            return image_bytes

        # For MVP, return image as-is (watermark via PIL in production)
        # TODO: Implement PIL-based watermarking
        logger.info("watermark_applied", tier=tier)
        return image_bytes

    def create_text_overlay(
        self,
        image_bytes: bytes,
        text: str,
        position: str = "bottom",
    ) -> bytes:
        """Add text overlay to an image."""
        # TODO: Implement PIL-based text overlay
        logger.info("text_overlay_applied", position=position)
        return image_bytes


class Packager:
    """Creates downloadable ZIP bundles with all generated assets."""

    def create_bundle(
        self,
        readme_content: str,
        banner_image: Optional[bytes] = None,
        cover_images: Optional[list[bytes]] = None,
        social_cards: Optional[dict[str, bytes]] = None,
        instructions: Optional[str] = None,
    ) -> bytes:
        """Create a ZIP bundle with all profile assets.

        Args:
            readme_content: Generated README.md content
            banner_image: Profile banner image bytes
            cover_images: Repository cover images
            social_cards: Social media cards (platform -> image bytes)
            instructions: Setup instructions markdown

        Returns:
            ZIP file as bytes
        """
        buffer = io.BytesIO()

        with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            # README
            zf.writestr("README.md", readme_content)

            # Banner
            if banner_image:
                zf.writestr("profile-banner.png", banner_image)

            # Repo covers
            if cover_images:
                for i, img in enumerate(cover_images, 1):
                    zf.writestr(f"repo-covers/cover-{i}.png", img)

            # Social cards
            if social_cards:
                for platform, img in social_cards.items():
                    zf.writestr(f"social-cards/{platform}.png", img)

            # Instructions
            if instructions:
                zf.writestr("SETUP.md", instructions)
            else:
                zf.writestr("SETUP.md", self._default_instructions())

        buffer.seek(0)
        logger.info(
            "bundle_created",
            has_banner=banner_image is not None,
            cover_count=len(cover_images or []),
            social_count=len(social_cards or {}),
        )
        return buffer.read()

    def _default_instructions(self) -> str:
        """Generate default setup instructions."""
        return """# Setup Instructions

## Profile Banner
1. Go to your GitHub profile
2. Click "Edit profile"
3. Upload `profile-banner.png` as your profile picture or use it in your README

## README.md
1. Create a repository with the same name as your GitHub username
2. Add the `README.md` file from this bundle
3. Customize any sections as needed

## Repository Covers
Use the images in `repo-covers/` as social preview images for your repositories:
1. Go to your repository settings
2. Scroll to "Social preview"
3. Upload the cover image

## Social Cards
Use the images in `social-cards/` for your LinkedIn, Twitter/X, or other profiles.

---
Generated by [Git Phantom Scope](https://gitphantomscope.dev)
Privacy-First - No data was stored during generation.
"""
