"""Rendering & Packaging Service.

Handles watermark application, text overlays, and ZIP bundle creation.
Generated assets are stored temporarily with auto-delete after TTL.

PRIVACY: Generated assets auto-delete after 4 hours.
"""

from __future__ import annotations

import io
import zipfile

from PIL import Image, ImageDraw, ImageFont

from app.logging_config import get_logger

logger = get_logger(__name__)


class Renderer:
    """Handles image post-processing and watermarking."""

    WATERMARK_TEXT = "Generated by Git Phantom Scope"
    WATERMARK_URL = "gitphantomscope.dev"

    def add_watermark(self, image_bytes: bytes, tier: str = "free") -> bytes:
        """Add watermark to generated images.

        Free tier: Visible watermark (semi-transparent, bottom-right)
        Pro tier: Small, subtle watermark (lower opacity)
        Enterprise: No watermark
        """
        if tier == "enterprise":
            return image_bytes

        try:
            img = Image.open(io.BytesIO(image_bytes)).convert("RGBA")
            overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
            draw = ImageDraw.Draw(overlay)

            # Scale font size relative to image width
            font_size = max(14, img.width // 50)
            try:
                font = ImageFont.truetype("arial.ttf", font_size)
            except OSError:
                font = ImageFont.load_default()

            watermark_text = f"{self.WATERMARK_TEXT} | {self.WATERMARK_URL}"

            # Measure text size
            bbox = draw.textbbox((0, 0), watermark_text, font=font)
            text_width = bbox[2] - bbox[0]
            text_height = bbox[3] - bbox[1]

            # Position: bottom-right with padding
            padding = max(10, img.width // 80)
            x = img.width - text_width - padding
            y = img.height - text_height - padding

            # Opacity based on tier
            alpha = 180 if tier == "free" else 80  # free=visible, pro=subtle

            # Draw semi-transparent background
            bg_padding = 6
            draw.rectangle(
                [
                    x - bg_padding,
                    y - bg_padding,
                    x + text_width + bg_padding,
                    y + text_height + bg_padding,
                ],
                fill=(0, 0, 0, alpha // 2),
            )

            # Draw text
            draw.text((x, y), watermark_text, fill=(255, 255, 255, alpha), font=font)

            # Composite
            watermarked = Image.alpha_composite(img, overlay)
            output = io.BytesIO()
            watermarked.save(output, format="PNG")
            output.seek(0)

            logger.info("watermark_applied", tier=tier)
            return output.read()

        except Exception:
            logger.warning("watermark_failed_returning_original", tier=tier)
            return image_bytes

    def create_text_overlay(
        self,
        image_bytes: bytes,
        text: str,
        position: str = "bottom",
    ) -> bytes:
        """Add text overlay to an image.

        Args:
            image_bytes: Source image bytes
            text: Text to overlay
            position: 'top', 'center', or 'bottom'
        """
        try:
            img = Image.open(io.BytesIO(image_bytes)).convert("RGBA")
            overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
            draw = ImageDraw.Draw(overlay)

            font_size = max(18, img.width // 30)
            try:
                font = ImageFont.truetype("arial.ttf", font_size)
            except OSError:
                font = ImageFont.load_default()

            bbox = draw.textbbox((0, 0), text, font=font)
            text_width = bbox[2] - bbox[0]
            text_height = bbox[3] - bbox[1]

            # Horizontal center
            x = (img.width - text_width) // 2

            # Vertical position
            padding = max(20, img.height // 20)
            if position == "top":
                y = padding
            elif position == "center":
                y = (img.height - text_height) // 2
            else:  # bottom
                y = img.height - text_height - padding

            # Semi-transparent background bar
            bar_padding = 10
            draw.rectangle(
                [0, y - bar_padding, img.width, y + text_height + bar_padding],
                fill=(0, 0, 0, 140),
            )

            # Draw text
            draw.text((x, y), text, fill=(255, 255, 255, 230), font=font)

            result = Image.alpha_composite(img, overlay)
            output = io.BytesIO()
            result.save(output, format="PNG")
            output.seek(0)

            logger.info("text_overlay_applied", position=position)
            return output.read()

        except Exception:
            logger.warning("text_overlay_failed_returning_original")
            return image_bytes


class Packager:
    """Creates downloadable ZIP bundles with all generated assets."""

    def create_bundle(
        self,
        readme_content: str,
        banner_image: bytes | None = None,
        cover_images: list[bytes] | None = None,
        social_cards: dict[str, bytes] | None = None,
        instructions: str | None = None,
    ) -> bytes:
        """Create a ZIP bundle with all profile assets.

        Args:
            readme_content: Generated README.md content
            banner_image: Profile banner image bytes
            cover_images: Repository cover images
            social_cards: Social media cards (platform -> image bytes)
            instructions: Setup instructions markdown

        Returns:
            ZIP file as bytes
        """
        buffer = io.BytesIO()

        with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            # README
            zf.writestr("README.md", readme_content)

            # Banner
            if banner_image:
                zf.writestr("profile-banner.png", banner_image)

            # Repo covers
            if cover_images:
                for i, img in enumerate(cover_images, 1):
                    zf.writestr(f"repo-covers/cover-{i}.png", img)

            # Social cards
            if social_cards:
                for platform, img in social_cards.items():
                    zf.writestr(f"social-cards/{platform}.png", img)

            # Instructions
            if instructions:
                zf.writestr("SETUP.md", instructions)
            else:
                zf.writestr("SETUP.md", self._default_instructions())

        buffer.seek(0)
        logger.info(
            "bundle_created",
            has_banner=banner_image is not None,
            cover_count=len(cover_images or []),
            social_count=len(social_cards or {}),
        )
        return buffer.read()

    def _default_instructions(self) -> str:
        """Generate default setup instructions."""
        return """# Setup Instructions

## Profile Banner
1. Go to your GitHub profile
2. Click "Edit profile"
3. Upload `profile-banner.png` as your profile picture or use it in your README

## README.md
1. Create a repository with the same name as your GitHub username
2. Add the `README.md` file from this bundle
3. Customize any sections as needed

## Repository Covers
Use the images in `repo-covers/` as social preview images for your repositories:
1. Go to your repository settings
2. Scroll to "Social preview"
3. Upload the cover image

## Social Cards
Use the images in `social-cards/` for your LinkedIn, Twitter/X, or other profiles.

---
Generated by [Git Phantom Scope](https://gitphantomscope.dev)
Privacy-First - No data was stored during generation.
"""
